# Generated by Django 2.2.5 on 2019-09-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120, null=True)),
                ('event_type', models.SmallIntegerField(choices=[(0, 'invite'), (1, 'invite by link')], default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('status', models.SmallIntegerField(choices=[(0, 'pending'), (1, 'yes'), (2, 'maybe'), (3, 'no')], default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.Event')),
            ],
            options={
                'unique_together': {('event', 'username')},
            },
        ),
    ]
