# Generated by Django 2.2.5 on 2019-09-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190920_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
