# Generated by Django 2.2.5 on 2019-09-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20190921_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'invite'), (1, 'invite by link')], default=0),
        ),
    ]
