# Generated by Django 2.2.5 on 2019-09-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
