# Generated by Django 2.2.5 on 2019-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20190921_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
