# Generated by Django 2.2.5 on 2019-09-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
