# Generated by Django 2.2.5 on 2019-09-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20190921_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
